### ISSUE TITLE
Truffle config is broken when using INFURA_API_KEY rather than custom node

### ISSUE THREAD

**Issue by mrice32** [UMAprotocol/protocol#1888]
**Description**

The truffle config doesn't correctly resolve the infura url when using the INFURA_API_KEY env variable.

```
yarn truffle console --network mainnet_mnemonic
yarn run v1.22.4
$ /Users/matt/git/protocol/node_modules/.bin/truffle console --network mainnet_mnemonic
Error: The network id specified in the truffle config (1) does not match the one returned by the network (42).  Ensure that both the network and the provider are properly configured.
    at Object.detectAndSetNetworkId (/Users/matt/git/protocol/node_modules/truffle/build/webpack:/packages/environment/environment.js:97:1)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.detect (/Users/matt/git/protocol/node_modules/truffle/build/webpack:/packages/environment/environment.js:24:1)
Truffle v5.1.41 (core: 5.1.41)
Node v12.18.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Reproduction**

1. Set `INFURA_API_KEY` in the env, but do not set `CUSTOM_NODE_URL`.
2. Run `yarn truffle console --network mainnet_mnemonic` from root.

**Expected Behavior**

Truffle should connect to the correct network.

**Additional Context**

The problem is that the `name` variable is undefined when [this line](https://github.com/UMAprotocol/protocol/blob/b3bdd88874bd67207f5d60978fd20161c42ebd23/packages/common/src/TruffleConfig.js#L39) is hit. It was previously called in the context of a function that provided the `name`.

**Comment by mrice32** [comment]
I'm actually going to work on fixing this.
