### ISSUE TITLE
yarn (install mono repo) - node v12.19 > scrypt install error

### ISSUE THREAD

**Issue by SvenMeyer** [UMAprotocol/protocol#2288]
OS : Manjaro / Arch Linux / Linux 5.8.18-1-MANJARO

```
$ cd protocol/
$ node --version
v12.19.0
$ yarn --version
1.22.10

$ yarn
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
warning mini-css-extract-plugin@0.5.0: Invalid bin field for "mini-css-extract-plugin".
warning url-loader@1.1.2: Invalid bin field for "url-loader".
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.0.6: The platform "linux" is incompatible with this module.
info "fsevents@2.0.6" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-config-react-app@5.2.1" has unmet peer dependency "@typescript-eslint/eslint-plugin@2.x".
warning " > eslint-config-react-app@5.2.1" has unmet peer dependency "@typescript-eslint/parser@2.x".
warning " > eslint-config-react-app@5.2.1" has incorrect peer dependency "eslint@6.x".
warning " > eslint-config-react-app@5.2.1" has incorrect peer dependency "eslint-plugin-react-hooks@1.x || 2.x".
warning " > eslint-plugin-react-hooks@3.0.0" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".
warning "workspace-aggregator-b7db9cdc-052b-4c1c-a214-9d58b59b804c > @uma/voter-dapp > @apollo/client@3.1.3" has unmet peer dependency "subscriptions-transport-ws@^0.9.0".
warning "workspace-aggregator-b7db9cdc-052b-4c1c-a214-9d58b59b804c > @uma/voter-dapp > @material-ui/icons@3.0.2" has incorrect peer dependency "@material-ui/core@^3.0.0".
warning "workspace-aggregator-b7db9cdc-052b-4c1c-a214-9d58b59b804c > @uma/core > @nomiclabs/buidler-truffle5 > @nomiclabs/truffle-contract@4.1.15" has unmet peer dependency "web3-core-promievent@^1.2.1".
warning "workspace-aggregator-b7db9cdc-052b-4c1c-a214-9d58b59b804c > @uma/core > @nomiclabs/buidler-truffle5 > @nomiclabs/truffle-contract@4.1.15" has unmet peer dependency "web3-eth-abi@^1.2.1".
warning "workspace-aggregator-b7db9cdc-052b-4c1c-a214-9d58b59b804c > @uma/core > @nomiclabs/buidler-truffle5 > @nomiclabs/truffle-contract@4.1.15" has unmet peer dependency "web3-utils@^1.2.1".
warning "workspace-aggregator-b7db9cdc-052b-4c1c-a214-9d58b59b804c > @uma/core > buidler-gas-reporter > eth-gas-reporter@0.2.18" has unmet peer dependency "@codechecks/client@^0.1.0".
warning "workspace-aggregator-b7db9cdc-052b-4c1c-a214-9d58b59b804c > @uma/voter-dapp > react-scripts > @typescript-eslint/eslint-plugin@1.6.0" has unmet peer dependency "typescript@*".
warning "workspace-aggregator-b7db9cdc-052b-4c1c-a214-9d58b59b804c > @uma/voter-dapp > react-scripts > @typescript-eslint/parser@1.6.0" has unmet peer dependency "typescript@*".
warning "workspace-aggregator-b7db9cdc-052b-4c1c-a214-9d58b59b804c > @uma/voter-dapp > react-scripts > @typescript-eslint/eslint-plugin > @typescript-eslint/typescript-estree@1.6.0" has unmet peer dependency "typescript@*".
warning "workspace-aggregator-b7db9cdc-052b-4c1c-a214-9d58b59b804c > @uma/voter-dapp > react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning "workspace-aggregator-b7db9cdc-052b-4c1c-a214-9d58b59b804c > @uma/common > @truffle/hdwallet-provider > @trufflesuite/web3-provider-engine > eth-block-tracker > @babel/plugin-transform-runtime@7.11.0" has unmet peer dependency "@babel/core@^7.0.0-0".
[4/4] Building fresh packages...
[18/40] ⠐ keccak
[19/40] ⠐ web3
[20/40] ⠐ secp256k1
[4/40] ⠐ scrypt
warning Error running install script for optional dependency: "/home/sum/DEV/DEFI/UMA/protocol/node_modules/scrypt: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/sum/DEV/DEFI/UMA/protocol/node_modules/scrypt
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.1
gyp info using node@12.19.0 | linux | x64
gyp info find Python using Python version 3.8.3 found at \"/home/sum/anaconda3/bin/python\"
gyp info spawn /home/sum/anaconda3/bin/python
gyp info spawn args [
gyp info spawn args   '/home/sum/DEV/DEFI/UMA/protocol/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/sum/DEV/DEFI/UMA/protocol/node_modules/scrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/sum/DEV/DEFI/UMA/protocol/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/sum/.cache/node-gyp/12.19.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/sum/.cache/node-gyp/12.19.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/sum/DEV/DEFI/UMA/protocol/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/sum/.cache/node-gyp/12.19.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/sum/DEV/DEFI/UMA/protocol/node_modules/scrypt',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/sum/DEV/DEFI/UMA/protocol/node_modules/scrypt/build'
  SOLINK_MODULE(target) Release/obj.target/copied_files.node
  COPY Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  AR(target) Release/obj.target/scrypt_wrapper.a
  COPY Release/scrypt_wrapper.a
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/crypto/crypto_scrypt.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/crypto/crypto_scrypt_smix.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/util/warnp.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/alg/sha256.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/libcperciva/util/insecure_memzero.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.0/lib/scryptenc/scryptenc_cpuperf.o
  AR(target) Release/obj.target/scrypt_lib.a
  COPY Release/scrypt_lib.a
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:0,
                 from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_common.h: In constructor 'NodeScrypt::Params::Params(const v8::Local<v8::Object>&)':
../src/node-boilerplate/inc/scrypt_common.h:39:48: warning: 'v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
       N(obj->Get(Nan::New(\"N\").ToLocalChecked())->Uint32Value()),
                                                ^
In file included from /home/sum/.cache/node-gyp/12.19.0/include/node/v8-internal.h:14:0,
                 from /home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:27,
                 from /home/sum/.cache/node-gyp/12.19.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:3553:51: note: declared here
   V8_DEPRECATED(\"Use maybe version\", Local<Value> Get(Local<Value> key));
                                                   ^
/home/sum/.cache/node-gyp/12.19.0/include/node/v8config.h:328:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:0,
                 from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_common.h:39:63: error: no matching function for call to 'v8::Value::Uint32Value()'
       N(obj->Get(Nan::New(\"N\").ToLocalChecked())->Uint32Value()),
                                                               ^
In file included from /home/sum/.cache/node-gyp/12.19.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:56,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:2707:41: note: candidate: v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                         ^
/home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:2707:41: note:   candidate expects 1 argument, 0 provided
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:0,
                 from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_common.h:40:48: warning: 'v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
       r(obj->Get(Nan::New(\"r\").ToLocalChecked())->Uint32Value()),
                                                ^
In file included from /home/sum/.cache/node-gyp/12.19.0/include/node/v8-internal.h:14:0,
                 from /home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:27,
                 from /home/sum/.cache/node-gyp/12.19.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:3553:51: note: declared here
   V8_DEPRECATED(\"Use maybe version\", Local<Value> Get(Local<Value> key));
                                                   ^
/home/sum/.cache/node-gyp/12.19.0/include/node/v8config.h:328:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:0,
                 from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_common.h:40:63: error: no matching function for call to 'v8::Value::Uint32Value()'
       r(obj->Get(Nan::New(\"r\").ToLocalChecked())->Uint32Value()),
                                                               ^
In file included from /home/sum/.cache/node-gyp/12.19.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:56,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:2707:41: note: candidate: v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                         ^
/home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:2707:41: note:   candidate expects 1 argument, 0 provided
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:0,
                 from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_common.h:41:48: warning: 'v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
       p(obj->Get(Nan::New(\"p\").ToLocalChecked())->Uint32Value()) {}
                                                ^
In file included from /home/sum/.cache/node-gyp/12.19.0/include/node/v8-internal.h:14:0,
                 from /home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:27,
                 from /home/sum/.cache/node-gyp/12.19.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:3553:51: note: declared here
   V8_DEPRECATED(\"Use maybe version\", Local<Value> Get(Local<Value> key));
                                                   ^
/home/sum/.cache/node-gyp/12.19.0/include/node/v8config.h:328:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../src/node-boilerplate/inc/scrypt_async.h:28:0,
                 from ../src/node-boilerplate/inc/scrypt_params_async.h:28,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_common.h:41:63: error: no matching function for call to 'v8::Value::Uint32Value()'
       p(obj->Get(Nan::New(\"p\").ToLocalChecked())->Uint32Value()) {}
                                                               ^
In file included from /home/sum/.cache/node-gyp/12.19.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:56,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:2707:41: note: candidate: v8::Maybe<unsigned int> v8::Value::Uint32Value(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
                                         ^
/home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:2707:41: note:   candidate expects 1 argument, 0 provided
In file included from ../src/node-boilerplate/inc/scrypt_params_async.h:28:0,
                 from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_async.h: In member function 'virtual void ScryptAsyncWorker::HandleErrorCallback()':
../src/node-boilerplate/inc/scrypt_async.h:53:29: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
       callback->Call(1, argv);
                             ^
In file included from ../src/node-boilerplate/scrypt_params_async.cc:1:0:
../../nan/nan.h:1742:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:0:
../src/node-boilerplate/inc/scrypt_params_async.h: In constructor 'ScryptParamsAsyncWorker::ScryptParamsAsyncWorker(Nan::NAN_METHOD_ARGS_TYPE)':
../src/node-boilerplate/inc/scrypt_params_async.h:35:36: error: no matching function for call to 'v8::Value::NumberValue()'
       maxtime(info[0]->NumberValue()),
                                    ^
In file included from /home/sum/.cache/node-gyp/12.19.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:56,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:2704:39: note: candidate: v8::Maybe<double> v8::Value::NumberValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
                                       ^
/home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:2704:39: note:   candidate expects 1 argument, 0 provided
In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:0:
../src/node-boilerplate/inc/scrypt_params_async.h:36:39: error: no matching function for call to 'v8::Value::NumberValue()'
       maxmemfrac(info[1]->NumberValue()),
                                       ^
In file included from /home/sum/.cache/node-gyp/12.19.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:56,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:2704:39: note: candidate: v8::Maybe<double> v8::Value::NumberValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
                                       ^
/home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:2704:39: note:   candidate expects 1 argument, 0 provided
In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:0:
../src/node-boilerplate/inc/scrypt_params_async.h:37:36: error: no matching function for call to 'v8::Value::IntegerValue()'
       maxmem(info[2]->IntegerValue()),
                                    ^
In file included from /home/sum/.cache/node-gyp/12.19.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:56,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:2705:40: note: candidate: v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
                                        ^
/home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:2705:40: note:   candidate expects 1 argument, 0 provided
In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:0:
../src/node-boilerplate/inc/scrypt_params_async.h:38:39: error: no matching function for call to 'v8::Value::IntegerValue()'
       osfreemem(info[3]->IntegerValue())
                                       ^
In file included from /home/sum/.cache/node-gyp/12.19.0/include/node/node.h:67:0,
                 from ../../nan/nan.h:56,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:2705:40: note: candidate: v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
                                        ^
/home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:2705:40: note:   candidate expects 1 argument, 0 provided
../src/node-boilerplate/scrypt_params_async.cc: In member function 'virtual void ScryptParamsAsyncWorker::HandleOKCallback()':
../src/node-boilerplate/scrypt_params_async.cc:23:67: warning: 'bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
   obj->Set(Nan::New(\"N\").ToLocalChecked(), Nan::New<Integer>(logN));
                                                                   ^
In file included from /home/sum/.cache/node-gyp/12.19.0/include/node/v8-internal.h:14:0,
                 from /home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:27,
                 from /home/sum/.cache/node-gyp/12.19.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:3499:22: note: declared here
                 bool Set(Local<Value> key, Local<Value> value));
                      ^
/home/sum/.cache/node-gyp/12.19.0/include/node/v8config.h:328:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
../src/node-boilerplate/scrypt_params_async.cc:24:64: warning: 'bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
   obj->Set(Nan::New(\"r\").ToLocalChecked(), Nan::New<Integer>(r));
                                                                ^
In file included from /home/sum/.cache/node-gyp/12.19.0/include/node/v8-internal.h:14:0,
                 from /home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:27,
                 from /home/sum/.cache/node-gyp/12.19.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:3499:22: note: declared here
                 bool Set(Local<Value> key, Local<Value> value));
                      ^
/home/sum/.cache/node-gyp/12.19.0/include/node/v8config.h:328:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
../src/node-boilerplate/scrypt_params_async.cc:25:64: warning: 'bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)' is deprecated: Use maybe version [-Wdeprecated-declarations]
   obj->Set(Nan::New(\"p\").ToLocalChecked(), Nan::New<Integer>(p));
                                                                ^
In file included from /home/sum/.cache/node-gyp/12.19.0/include/node/v8-internal.h:14:0,
                 from /home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:27,
                 from /home/sum/.cache/node-gyp/12.19.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/sum/.cache/node-gyp/12.19.0/include/node/v8.h:3499:22: note: declared here
                 bool Set(Local<Value> key, Local<Value> value));
                      ^
/home/sum/.cache/node-gyp/12.19.0/include/node/v8config.h:328:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
../src/node-boilerplate/scrypt_params_async.cc:32:25: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   callback->Call(2, argv);
                         ^
In file included from ../src/node-boilerplate/scrypt_params_async.cc:1:0:
../../nan/nan.h:1742:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
make: *** [scrypt.target.mk:131: Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o] Error 1
make: Leaving directory '/home/sum/DEV/DEFI/UMA/protocol/node_modules/scrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/sum/DEV/DEFI/UMA/protocol/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.8.18-1-MANJARO
gyp ERR! command \"/home/sum/.nvm/versions/node/v12.19.0/bin/node\" \"/home/sum/DEV/DEFI/UMA/protocol/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /home/sum/DEV/DEFI/UMA/protocol/node_modules/scrypt
Done in 105.44s.
$
```

**Comment by SvenMeyer** [comment]
https://github.com/ethereum/web3.js/issues/3408

**Comment by daywiss** [comment]
This looks to be an issue with the scrypt module, its [no longer maintained](https://github.com/barrysteyn/node-scrypt) and is not compatible with node 12. Node has a [native replacement](https://nodejs.org/api/crypto.html#crypto_crypto_scrypt_password_salt_keylen_options_callback). I have the same error when installing but haven't noticed anything detrimental using the repo. I think the error might be misleading because its shows up as an optional dependency in your log: 

```
[4/40] ⠐ scrypt
warning Error running install script for optional dependency: "/home/sum/DEV/DEFI/UMA/protocol/node_modules/scrypt: Command failed.
Exit code: 1
```

I'm not quite sure what package is currently depending on it but nothing is broken as far as i know. Let us know though if you run into a problem running things.
