### ISSUE TITLE
[solution] yarn install fails on Ubuntu 21.04 stock due to missing libudev-dev & libusb-1.0-0-dev

### ISSUE THREAD

**Issue by dadaphl** [UMAprotocol/protocol#3715]
**Description**

`yarn` fails on Ubuntu 21.04

**Reproduction**

1. Clone repository
2. `yarn`

fails because of node-gyp node-hid

```
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/philipp/dev/sol/protocol/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi-linux-hidraw/hidapi/linux/hid.o
../hidapi/linux/hid.c:44:10: fatal error: libudev.h: No such file or directory
   44 | #include <libudev.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [hidapi-linux-hidraw.target.mk:111: Release/obj.target/hidapi-linux-hidraw/hidapi/linux/hid.o] Error 1
make: Leaving directory '/home/philipp/dev/sol/protocol/node_modules/node-hid/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/philipp/dev/sol/protocol/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Linux 5.11.0-41-generic
gyp ERR! command \"/home/philipp/.nvm/versions/node/v14.18.1/bin/node\" \"/home/philipp/dev/sol/protocol/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /home/philipp/dev/sol/protocol/node_modules/node-hid
Done in 32.53s.
```

With libudev-dev installed
```
... more stuff
In file included from ../src/HID.cc:34:
../src/HID.cc: At global scope:
/home/philipp/.cache/node-gyp/14.18.1/include/node/node.h:787:7: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  787 |       (node::addon_register_func) (regfunc),                          \\\n      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/philipp/.cache/node-gyp/14.18.1/include/node/node.h:821:3: note: in expansion of macro ‘NODE_MODULE_X’
  821 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/HID.cc:646:3: note: in expansion of macro ‘NODE_MODULE’
  646 |   NODE_MODULE(HID, init);
      |   ^~~~~~~~~~~
/usr/bin/ld: cannot find -lusb-1.0
collect2: error: ld returned 1 exit status
make: *** [HID-hidraw.target.mk:152: Release/obj.target/HID-hidraw.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/philipp/dev/sol/protocol/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Linux 5.11.0-41-generic
gyp ERR! command \"/home/philipp/.nvm/versions/node/v14.18.1/bin/node\" \"/home/philipp/dev/sol/protocol/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /home/philipp/dev/sol/protocol/node_modules/node-hid
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v7.1.2
Done in 31.13s.
```

**Expected Behavior**

install dependencies without error

**Version and OS Info**

commit 952874792bf5d12bbfc12470997a0569aa4edcd8 (HEAD -> master, origin/master, origin/HEAD)
Author: nicholaspai <9457025+nicholaspai@users.noreply.github.com>
Date:   Thu Dec 9 09:49:07 2021 -0500

➜  protocol git:(master) node -v
v14.18.1

➜  protocol git:(master) lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.04
Release:        21.04
Codename:       hirsute

**Additional Context**
```
➜  protocol git:(master) apt install libudev-dev libusb-1.0-0-dev
```
fixes it.
This libs are not installed by default on a Ubuntu installation with build-essential and cmake. So either it should be in the requirements section of the README.md or your dependencies should be reconsidered. A qick'n dirty `Ack` revealed that the issue comes from `@ethersproject/hardware-wallets` depending on usb / udev related functionality. Question is, should hardware wallet functionality be a strict dependency for your project?
```
@ethersproject/hardware-wallets/node_modules/node-hid/hidapi/configure.ac
71:     PKG_CHECK_MODULES([libusb], [libusb-1.0 >= 1.0.9], true, [hidapi_lib_error libusb-1.0])
```

**Comment by dadaphl** [comment]
# Solution
install libudev-dev and libusb-1.0-0-dev
```
apt install libudev-dev libusb-1.0-0-dev
```

**Comment by mrice32** [comment]
Yep, these instructions are included in our docs I believe and are included in the dockerfile.
